# Generated by Django 4.1.7 on 2023-03-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AddField(
            model_name='movie',
            name='file',
            field=models.FileField(default=None, upload_to='movies'),
        ),
        migrations.DeleteModel(
            name='video',
        ),
    ]
