# Generated by Django 4.1.7 on 2023-03-22 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_movie_video_movie_file_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
    ]
