# Generated by Django 4.1.7 on 2023-03-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_remove_movie_image_movie_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
