# Generated by Django 4.1.7 on 2023-03-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='desc1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
