# Generated by Django 4.1.7 on 2023-03-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_movie_desc1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='movie',
            name='dir',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='dur',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='prod',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='screenplay',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
