# Generated by Django 4.1.7 on 2023-03-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_alter_movie_rate_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
